subplot(411)
plot(Data.time, Data.signals(1).values)
subplot(412)
plot(Data.time, Data.signals(2).values)
subplot(413)
plot(Data.time, Data.signals(3).values)
subplot(414)
plot(Data.time, Data.signals(4).values)